apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    app: hello
spec:
  containers:
    - name: hello
      image: busybox
      command: ['sh', '-c']
      args: ['echo "Hello, Kubernetes!" && sleep 3600']
  restartPolicy: OnFailure
