apiVersion: v1
kind: ConfigMap
metadata:
  name: demo
data:
  # property-like keys; each key maps to a simple value
  environment: production
  foo: bar

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
