apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: web
      image: nginx:1.14.2
      command: ['sh', '-c']
      args: ['echo "$environment" && sleep 3600']
      ports:
        - containerPort: 80
      env:
        - name: environment
          valueFrom:
            configMapKeyRef:
              name: demo
              key: environment
        - name: foo
          valueFrom:
            configMapKeyRef:
              name: demo
              key: foo
