apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: web
      image: nginx:1.14.2
      command: ['sh', '-c']
      args: ['ls -la /config && sleep 3600']
      ports:
        - containerPort: 80
      volumeMounts:
      - name: config
        mountPath: /config
        readOnly: true
  volumes:
    - name: config
      configMap:
        name: demo
        # items:
        # - key: game.properties
        #   path: game.properties
        # - key: user-interface.properties
        #   path: user-interface.properties
