apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: private-reg-container
      image: images.my-company.example/log-aggregator:v6
